-- CreateEnum
CREATE TYPE "Cargo" AS ENUM ('COORDENADOR_GERAL', 'FORMADOR', 'COORDENADOR_FREQUENCIA', 'COORDENADOR_CAIXINHA', 'ANIMADOR_FREQUENCIA', 'ANIMADOR_CAIXINHA', 'ANIMADOR');

-- AlterTable
ALTER TABLE "Animador" ADD COLUMN     "cargo" "Cargo" NOT NULL DEFAULT 'ANIMADOR';
